from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "seatmap-canvas"
owner = "alisaitteke"
authors = [
    { username = "alisaitteke", signature = "Ali Sait Teke"}
]
