from_latest_tag = true
tag_prefix = "v"

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "seatmap-canvas"
owner = "alisaitteke"
authors = [
    { username = "alisaitteke", signature = "Ali Sait Teke"}
]
