name: Create Pull Request
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B develop -H master --title 'Merge develop into master' --body 'Created by Github action'