name: NodeJS with Webpack
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install
    - name: Build production bundle
      uses: borales/actions-yarn@v4
      with:
        cmd: build